version: 2
jobs:
  feat2dev_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "d202"
      - RUN_WS_PLAN: "true"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            chmod +x .circleci/update_asg_ws.sh
            .circleci/update_asg_ws.sh
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false
  dev_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "d202"
      - RUN_WS_PLAN: "true"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            chmod +x .circleci/lint.sh
            chmod +x .circleci/validate.sh
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            chmod +x .circleci/update_asg_ws.sh
            .circleci/update_asg_ws.sh
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/asg_tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  dev_apply_asg:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "d202"
      - RUN_WS_APPLY: "true"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - attach_workspace:
          at: plans
      - run: 
          name: update_asg
          command: |
            chmod +x .circleci/update_asg_ws.sh
            .circleci/update_asg_ws.sh
      - run: terraform apply -no-color -input=false -auto-approve plans/asg_tfm.plan
  dev_apply_dns:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "d202"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_dns
          command: |
            chmod +x .circleci/update_dns_ws.sh
            .circleci/update_dns_ws.sh
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/dns_tfm.plan
      - attach_workspace:
          at: plans
      - run: terraform apply -no-color -input=false -auto-approve plans/dns_tfm.plan
  dev2uat_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "t201"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            echo -e "acc_id = ${acc_id}" | tee -a env/${WKSPC}.tfvars
            echo -e "allowed_ips = ${allowed_ips}" | tee -a env/${WKSPC}.tfvars
            echo -e "cert_domain = ${cert_domain}" | tee -a env/${WKSPC}.tfvars
            echo -e "zone_id = ${zone_id}" | tee -a env/${WKSPC}.tfvars
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/tfm.plan
  uat_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "t201"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            echo -e "acc_id = ${acc_id}" | tee -a env/${WKSPC}.tfvars
            echo -e "allowed_ips = ${allowed_ips}" | tee -a env/${WKSPC}.tfvars
            echo -e "cert_domain = ${cert_domain}" | tee -a env/${WKSPC}.tfvars
            echo -e "zone_id = ${zone_id}" | tee -a env/${WKSPC}.tfvars
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  uat_apply:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "t201"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - attach_workspace:
          at: plans
      - run: terraform apply -no-color -input=false -auto-approve plans/tfm.plan
  uat2prd_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "p200"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            echo -e "acc_id = ${acc_id}" | tee -a env/${WKSPC}.tfvars
            echo -e "allowed_ips = ${allowed_ips}" | tee -a env/${WKSPC}.tfvars
            echo -e "cert_domain = ${cert_domain}" | tee -a env/${WKSPC}.tfvars
            echo -e "zone_id = ${zone_id}" | tee -a env/${WKSPC}.tfvars
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/tfm.plan
  prd_plan:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "p200"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: 
          name: lint-validate
          command: |
            .circleci/lint.sh
            .circleci/validate.sh
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC
      - run: 
          name: update_tfvars
          command: |
            echo -e "acc_id = ${acc_id}" | tee -a env/${WKSPC}.tfvars
            echo -e "allowed_ips = ${allowed_ips}" | tee -a env/${WKSPC}.tfvars
            echo -e "cert_domain = ${cert_domain}" | tee -a env/${WKSPC}.tfvars
            echo -e "zone_id = ${zone_id}" | tee -a env/${WKSPC}.tfvars
      - run: terraform plan -var-file=env/${WKSPC}.tfvars -no-color -input=false -out=plans/tfm.plan
      - persist_to_workspace:
          root: plans
          paths:
            - tfm.plan
  prd_apply:
    docker:
      - image: hashicorp/terraform:light
    environment: 
      - WKSPC: "p200"
    steps:
      - add_ssh_keys
      - checkout
      - run: 
          name: init
          command: |
            terraform init -input=false
            if [ $? != "0" ]; then exit $?; fi
      - run: mkdir -p plans
      - run: terraform workspace select $WKSPC      
      - attach_workspace:
          at: plans
      - run: terraform apply -no-color -input=false -auto-approve plans/tfm.plan
workflows:
  version: 2
  feat2dev:
    jobs:
      - feat2dev_plan:
          filters:
            branches:
              ignore: 
                - master
                - uat
                - dev    
      - dev_plan:
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat
                
      - dev_apply_asg:
          requires: 
            - dev_plan
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat
      - dev_hold_dns:
          type: approval
          requires: 
            - dev_apply_asg
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat
      - dev_apply_dns:
          requires: 
            - dev_hold_dns
          filters: 
            branches:
              only: dev
              ignore: 
                - master
                - uat   
  dev2uat:
    jobs:
      - dev2uat_plan:
          filters:
            branches:
              only: dev  
              ignore: 
                - master
                - uat
                
      - uat_plan:
          filters:
            branches:
              only: uat   
              ignore: 
                - master
                - dev         
      - uat_apply:
          requires: 
            - uat_plan
          filters:
            branches:
              only: uat
              ignore: 
                - master
                - dev  
  uat2prd:
    jobs:
    - uat2prd_plan:
        filters:
          branches:
            only: uat
            ignore: 
              - master
              - dev
    - prd_plan:
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev
    - prd_hold:
        type: approval
        requires:
          - prd_plan
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev
    - prd_apply:
        requires: 
          - prd_hold
        filters:
          branches:
            only: master
            ignore: 
              - uat
              - dev